### ISSUE TITLE
A little improvment?

### ISSUE THREAD

**Issue by IsabelleGiraud** [giskonsulenten/EasyTemplatePrint#6]
Hi

I would like to thank you for your plugin. It's so great that I have installed it on my 200 collegues' computers and we use it every day (they are not GIS specialist and it's really simple for them to use it)

So I would like to make a suggestion for a little improvement.
It would be perfect if when we launch the plugin, the proposed scale is directly the canvas scale.
So we don't have to change it if the canvas scale is properly chosen.

I don't know if you have time for this improvment, but thank you anyway.

Isabelle Giraud

**Comment by giskonsulenten** [comment]
Hi Isabella

Thank you for your mail. Exciting to know that people out there actually
use your stuff :-)
I will certainly look into your request.


Best regards / Med venlig hilsen

Jesper Jøker Eg

Mobiltlf.: +45 61 72 75 57 <+45%2061%2072%2075%2057>

LinkedIn-profil:  Jesper Jøker Eg
<https://dk.linkedin.com/in/jesper-j%C3%B8ker-eg-6588a359>
E-mail:  jesper@giskonsulenten.dk

Web:  https://www.giskonsulenten.dk/


Den fre. 22. jan. 2021 kl. 18.10 skrev IsabelleGiraud <
notifications@github.com>:

**Comment by giskonsulenten** [comment]
I have added a button to quickly input mapcanvas scale. Hope you will like it.

/Jesper

**Comment by IsabelleGiraud** [comment]
Hi Jesper 
      
      
      The new version is not available yet but I ll try it as soon as
      it'll be and keep you posted!
      
    
    Thank you very much, best regards. 
    
      
    Le 05/02/2021 à 15:31, >
      notifications (par Internet, dépôt
      bounces+848413-cb16-isabelle.giraud=herault.gouv.fr@sgmail.github.com)
      a écrit :
    
    
      I have added a button to quickly input mapcanvas scale. Hope
        you will like it.
      /Jesper
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/giskonsulenten/EasyTemplatePrint/issues/6#issuecomment-774067227",
"url": "https://github.com/giskonsulenten/EasyTemplatePrint/issues/6#issuecomment-774067227",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by IsabelleGiraud** [comment]
Hi Jesper

A big thanks for the new version, it works perfectly!
I translate it in french for my collegue : as you know probably, french people doesn't speak english as well as you do in northern countries... :-(

Best regards

Isabelle
